Added SOrder model and OrderItem model
viktoriia-maherko/online-book-store pull request #9
Opened 2023-09-29 14:41 UTC by viktoriia-maherko

2023-09-29 15:11 UTC, sokimaaa commented on src/main/java/com/example/springboot/controller/OrderController.java
> +            description = "Retrieve user's order history")
The summary and description do not describe the endpoint.

2023-09-29 15:12 UTC, sokimaaa commented on src/main/java/com/example/springboot/controller/OrderController.java
> +            description = "Retrieve user's order history")
duplication of the summary and description.

2023-09-29 15:15 UTC, sokimaaa commented on src/main/java/com/example/springboot/service/impl/OrderServiceImpl.java
> +        return null;
never return null. 

make this method void in case you need to return nothing.

2023-09-29 15:17 UTC, sokimaaa commented on src/main/java/com/example/springboot/repository/orderitem/OrderItemRepository.java
> +    OrderItem findOrderItemByIdAndOrderId(Long orderItemId, Long orderId);
if nothing is found then return null. 
consider using optional here.

2023-10-02 10:37 UTC, Rommelua requested changes

2023-10-02 10:37 UTC, Rommelua commented on src/main/java/com/example/springboot/service/impl/OrderServiceImpl.java
> +        order.setOrderDate(LocalDateTime.now());
add setTotal to order

2023-10-02 14:10 UTC, merged